# Generated by Django 2.1.3 on 2018-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='movie.Movie'),
        ),
    ]
